INSERT INTO organizations (Code,EN,FR)
VALUES
("AGR", "Agriculture and Agri-Food Canada", "Agriculture et Agroalimentaire Canada"), 
("BSF", "Canada Border Services Agency", "Agence des services frontaliers du Canada"), 
("CAP", "Parks Canada Agency", "Agence Parcs Canada"), 
("CCB", "The Jacques-Cartier and Champlain Bridges Incorporated", "Les Ponts Jacques-Cartier et Champlain Inc."), 
("CCM", "Old Port of Montreal Corporation Inc. (Canada Lands Company)", "Le Vieux-Port de Montréal Limitée (Société immobilière du Canada)"), 
("CMC", "Canadian Museum of History", "Musée canadien de l\'histoire"), 
("DFO", "Fisheries and Oceans Canada", "Pêches et Océans Canada"), 
("DND", "National Defence", "Défence nationale"), 
("DOE", "Environment Canada", "Environnement Canada"), 
("DUS", "Industry Canada", "Industrie Canada"), 
("DVA", "Veterans Affairs Canada", "Anciens Combattants Canada"), 
("EXT", "Foreign Affairs, Trade and Development Canada", "Affaires étrangères, Commerce et Développement Canada"), 
("ICA", "Canadian Food Inspection Agency", "Agence canadienne d’inspection des aliments"), 
("IIA", "Aboriginal Affairs and Northern Development Canada (Indian and Inuit Affairs Program)", "Affaires autochtones et Développement du Nord Canada (Programme des affaires indiennes et inuites)"), 
("INF", "Office of Infrastructure of Canada", "Bureau de l\'infrastructure du Canada"), 
("MAI", "Marine Atlantic", "Marine Atlantique"), 
("MOT", "Transport Canada", "Transports Canada"), 
("NCC", "National Capital Commission", "Commission de la Capitale nationale"), 
("NOR", "Aboriginal Affairs and Northern Development Canada (Northern Affairs Program)", "Affaires autochtones et Développement du Nord Canada (Programme des affaires du Nord)"), 
("NRC", "National Research Council", "Conseil national de recherches"), 
("PEN", "Correctional Service of Canada", "Service correctionnel du Canada"), 
("RCM", "Royal Canadian Mounted Police", "Gendarmerie royale du Canada"), 
("RSN", "Natural Resources Canada", "Ressources naturelles Canada"), 
("SHC", "Health Canada", "Santé Canada"), 
("SVC", "Public Works and Government Services Canada", "Travaux publics et Services gouvernementaux Canada"), 
("VIA", "VIA Rail Canada", "VIA Rail Canada");

